name: Deploy Frontend via CI/CD

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Simular validación
        run: echo "Validación de estructura completada (SIG_SOLUTIONS)"

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
