name: Deploy Frontend via CI/CD # GitHub Actions

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Simular validación
        run: echo "Validación de estructura completada (SIG_SOLUTIONS)"

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Desplegar a GitHub Pages
        uses: actions/deploy-pages@v2
